### ISSUE TITLE
非问题，alitajs/antd-plus 这个组件为啥没了？

### ISSUE THREAD

**Issue by X-neuron** [alitajs/ide-plugin#2]
"@alitajs/antd-plus" 这个组件 私有化了？ 还是 不准备开源了？ 还是 以后内置在antd了？

**Comment by xiaohuoni** [comment]
你是指 https://github.com/alitajs/ant-design-plus ？

**Comment by X-neuron** [comment]
嗯呢，是这个。可能是早先几天 ant design 当机，每次 ncu 到 ant-design-plus时 就卡住过不去了。
感谢！
